# Generated by Django 5.2.1 on 2025-05-22 22:14

import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=fernet_fields.fields.EncryptedCharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=fernet_fields.fields.EncryptedCharField(max_length=100),
        ),
    ]
